### ISSUE TITLE
request for dataset

### ISSUE THREAD

**Issue by Prathamesh-Rathi** [bhargav1000/Magnum-Opus#2]
can you plz provide dataset on which you trained it

**Comment by ghost** [comment]
Please Could you provide the training dataset ?

**Comment by bhargav1000** [comment]
> can you plz provide dataset on which you trained it

Sorry for the late reply, but due to confidentiality reasons I cannot share the dataset under any circumstances.

**Comment by bhargav1000** [comment]
Apologies for the late reply, but due to confidentiality issues I cannot share the dataset under any circumstances.
I appreciate your understanding.
