### ISSUE TITLE
Memory,RAM required for this project

### ISSUE THREAD

**Issue by Satishkumar0651** [bhargav1000/Magnum-Opus#3]
what was the memory ,RAM rrequired for this project?

**Comment by bhargav1000** [comment]
Hi Satish, I developed this project on 8GB of RAM with an Intel i3 CPU and the storage used was about 10GB. Overall, it's not too compute heavy but of course you are free to modify the code and have it run on GPU and use more storage depending on the size of your dataset.

I wish you the best of luck :)
